#!/bin/bash

working_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
app_path=$(dirname $working_dir)

svscan=/local/$USER/svscan

$app_path/bin/update_services

[[ $USER =~ qa ]] && exit # Skip sleep in QA environments

echo "Sleeping for 15 seconds, svstat should say up for at least 10 seconds."
sleep 15
svstat $svscan/app
